=== jcohen02/tempro/src/main/resources/Constraints/PRISMConstraints.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="http://libhpc.doc.ic.ac.uk/prism/constraints" 
        xmlns:prism="http://libhpc.doc.ic.ac.uk/prism/constraints" 
        elementFormDefault="qualified">

  <complexType name="variable">
    <sequence>
      <element name="domain">
        <complexType>
          <sequence>
            <element name="value" type="string" minOccurs="1" maxOccurs="unbounded"/>
          </sequence>
        </complexType>
      </element>
    </sequence>
    <!-- A unique identifier for the variable. This is used in mapping elements -->
    <attribute name="name" type="string" />
    <!-- The full path to the template node that this variable relates to.  
         This path can exclude the solver name which will be automatically added.  
         Path elements should be dot-separated. -->
    <attribute name="path" type="string" />
    <!-- Denotes whether a constraint variable is repeatable (i.e. it is 
         attached to a repeatable element and many independent instances of 
         this variable may appear in a template. *Replaced by local-group* -->
    <!-- <attribute name="repeatable" type="boolean" />  -->
    <!-- An ID that can be used to group sets of variables that are related 
         within a template subtree. Every instance of this group of variables 
         will have its constraints evaluated as an independent local set. -->
    <attribute name="local-group" type="string" />
  </complexType>

  <complexType name="variables">
    <sequence>
      <element name="variable" type="prism:variable" minOccurs="1" maxOccurs="unbounded"/>
    </sequence>
  </complexType>
  
  <complexType name="pair">
    <sequence>
      <element name="varvalue" minOccurs="2" maxOccurs="2">
        <complexType>
          <simpleContent>
            <extension base="string">
              <attribute name="var" type="string" />
            </extension>
          </simpleContent>
        </complexType>
      </element>
    </sequence>
  </complexType>
  
  <complexType name="mapping">
    <sequence>
      <element name="targetValue" type="string" minOccurs="1" maxOccurs="unbounded"/>
    </sequence>
    <attribute name="variable" type="string"/>
    <attribute name="varvalue" type="string"/>
    <attribute name="targetVariable" type="string"/>
  </complexType>
  
  <complexType name="constraints">
    <choice>
      <element name="pair" type="prism:pair" minOccurs="1" maxOccurs="unbounded"/>
      <element name="mapping" type="prism:mapping" minOccurs="1" maxOccurs="unbounded"/>
    </choice>
  </complexType>

  <element name="PrismConstraints">
    <complexType>
      <sequence>
        <!-- A simple description of the problem represented by this constraint
             set -->
        <element name="description" type="string" minOccurs="1" maxOccurs="1"/>
        <!-- This should be the solver name exactly as it appears in the root
             node of the tempss template tree -->
        <element name="solver" type="string" minOccurs="1" maxOccurs="1"/>
        <element name="variables" type="prism:variables"/>
        <element name="constraints" type="prism:constraints"/>
      </sequence>
    </complexType>
  </element>

</schema>

=== jcohen02/tempro/src/main/resources/Constraints/IncNSConstraints.xml
<?xml version="1.0" encoding="UTF-8"?> 
<PrismConstraints 
    xmlns="http://libhpc.doc.ic.ac.uk/prism/constraints"  
    xmlns:prism="http://libhpc.doc.ic.ac.uk/prism/constraints"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://libhpc.doc.ic.ac.uk/prism/constraints PRISMConstraints.xsd">
    
    <description>Constraints for the Nektar++ Incompressible Navier-Stokes Solver</description>
    
    <!-- This should be the solver name exactly as it appears in the root node
         of the tree that these constraints relate to. 
    -->
    <solver>IncompressibleNavierStokes</solver>
    
    <variables>
      <variable path="ProblemSpecification.Dimensions" name="Dimensions">
        <domain>
          <value>TwoDimensional</value>
          <value>ThreeDimensional</value>
        </domain>
      </variable>      

      <variable path="NumericalSpecification.SolverType" name="SolverType">
        <domain>
          <value>CoupledLinearNS</value>
          <value>VelocityCorrectionScheme</value>
        </domain>
      </variable>      

      <variable path="NumericalSpecification.SolverType.VelocityCorrectionScheme" name="VelocityCorrectionScheme">
        <domain>
          <value>Standard</value>
          <value>WeakPressure</value>
          <value>Mapping</value>
        </domain>
      </variable>      

      <variable path="NumericalSpecification.TimeIntegration.TimeIntegrationMethod" 
                name="TimeIntegrationMethod">
        <domain>
          <value>NotProvided</value>
          <value>IMEXOrder1</value>
          <value>IMEXOrder2</value>
          <value>IMEXOrder3</value>
          <value>DIRKOrder1</value>
          <value>ForwardEuler</value>
          <value>BackwardEuler</value>
          <value>ClassicalRungeKutta4</value>
          <value>BDFImplicitOrder1</value>
          <value>BDFImplicitOrder2</value>
        </domain>
      </variable>
      
      <variable path="NumericalSpecification.SimulationType" name="SimulationType">
        <domain>
          <value>DirectNumericalSimulation</value>
          <value>StabilityAnalysis</value>
          <value>SteadyStateStability</value>
        </domain>
      </variable>           

      <variable path="NumericalSpecification.SimulationType.DirectNumericalSimulation.Driver" name="Driver">
        <domain>
          <value>Adaptive</value>
          <value>Standard</value>
        </domain>
      </variable>           

      <variable path="NumericalSpecification.Projection" name="Projection">
        <domain>
          <value>ContinuousGalerkin</value>
          <value>DiscontinuousGalerkin</value>
          <value>MixedGalerkin</value>
        </domain>
      </variable>           

    </variables>
    
    <constraints>
      <!-- Mapping of driverType with mapping -->
      <mapping variable="Driver" varvalue="Adaptive" targetVariable="VelocityCorrectionScheme">
        <targetValue>Mapping</targetValue>
      </mapping>
      

      <!-- Mapping of solver type with time integration type -->
      <mapping variable="SolverType" varvalue="VelocityCorrectionScheme" targetVariable="TimeIntegrationMethod">
        <targetValue>IMEXOrder1</targetValue>
        <targetValue>IMEXOrder2</targetValue>
        <targetValue>IMEXOrder3</targetValue>
        <targetValue>DIRKOrder1</targetValue>
        <targetValue>ForwardEuler</targetValue>
        <targetValue>BackwardEuler</targetValue>
        <targetValue>ClassicalRungeKutta4</targetValue>
        <targetValue>BDFImplicitOrder1</targetValue>
        <targetValue>BDFImplicitOrder2</targetValue>
      </mapping>
      <mapping variable="SolverType" varvalue="CoupledLinearNS" targetVariable="TimeIntegrationMethod">
        <targetValue>NotProvided</targetValue>
      </mapping>

      <!-- Mapping of solver type with projection type -->
      <mapping variable="SolverType" varvalue="VelocityCorrectionScheme" targetVariable="Projection">
        <targetValue>ContinuousGalerkin</targetValue>
        <targetValue>DiscontinuousGalerkin</targetValue>
        <targetValue>MixedGalerkin</targetValue>
      </mapping>
      <mapping variable="SolverType" varvalue="CoupledLinearNS" targetVariable="Projection">
        <targetValue>ContinuousGalerkin</targetValue>
      </mapping>
      
    </constraints>              
                  
</PrismConstraints>

=== jcohen02/tempro/src/main/resources/Constraints/VideoPipeConstraints.xml
<?xml version="1.0" encoding="UTF-8"?>
<PrismConstraints
    xmlns="http://libhpc.doc.ic.ac.uk/prism/constraints"
    xmlns:prism="http://libhpc.doc.ic.ac.uk/prism/constraints"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://libhpc.doc.ic.ac.uk/prism/constraints PRISMConstraints.xsd">

    <description>Constraints for the Video Pipe example</description>

    <!-- This should be the solver name exactly as it appears in the root node
         of the tree that these constraints relate to.
    -->
    <solver>VideoPipe</solver>

    <variables>
      <variable path="Functions.Map" name="Map">
        <domain>
          <value>MapSequential</value>
          <value>MapParallel</value>
        </domain>
      </variable>

      <variable path="Functions.ConcVid" name="ConcVid">
        <domain>
          <value>ConcVidSequential</value>
          <value>ConcVidParallel</value>
        </domain>
      </variable>

      <variable path="Machines.Machine" name="Machine">
        <domain>
          <value>StandaloneServer</value>
          <value>PBSCluster</value>
          <value>OpenstackCloud</value>
          <value>AmazonEC2</value>
        </domain>
      </variable>

      <variable path="Users.User" name="User">
        <domain>
          <value>User1</value>
          <value>User2</value>
          <value>User3</value>
        </domain>
      </variable>



    </variables>

    <constraints>
      <!-- Constraint mappings for Equation Type -> AdvectionType -->
      <!--
           If an EquationType that has no advection term is selected
           (i.e. Laplace, Poisson, Helmholtz, SteadyDiffusionReaction,
           UnsteadyDiffusion or UnsteadyInviscidBurger), it is not valid to
           select an entry from NumericalAlgorithm -> AdvectionType and this
           must be switched off.
      -->

      <mapping variable="Map" varvalue="MapSequential" targetVariable="Machine">
        <targetValue>StandaloneServer</targetValue>
        <targetValue>AmazonEC2</targetValue>
      </mapping>

      <mapping variable="Map" varvalue="MapParallel" targetVariable="Machine">
        <targetValue>PBSCluster</targetValue>
        <targetValue>OpenstackCloud</targetValue>
      </mapping>

      <mapping variable="ConcVid" varvalue="ConcVidSequential" targetVariable="Machine">
        <targetValue>StandaloneServer</targetValue>
        <targetValue>AmazonEC2</targetValue>
      </mapping>

      <mapping variable="ConcVid" varvalue="ConcVidParallel" targetVariable="Machine">
        <targetValue>PBSCluster</targetValue>
        <targetValue>OpenstackCloud</targetValue>
      </mapping>

      <mapping variable="Map" varvalue="MapSequential" targetVariable="ConcVid">
        <targetValue>ConcVidSequential</targetValue>
      </mapping>

      <mapping variable="Map" varvalue="MapParallel" targetVariable="ConcVid">
        <targetValue>ConcVidParallel</targetValue>
      </mapping>

      <mapping variable="User" varvalue="User1" targetVariable="Machine">
        <targetValue>AmazonEC2</targetValue>
      </mapping>

      <mapping variable="User" varvalue="User2" targetVariable="Machine">
        <targetValue>PBSCluster</targetValue>
        <targetValue>StandaloneServer</targetValue>
        <targetValue>OpenstackCloud</targetValue>
      </mapping>

      <mapping variable="User" varvalue="User3" targetVariable="Machine">
        <targetValue>StandaloneServer</targetValue>
      </mapping>

    </constraints>

</PrismConstraints>
